### ISSUE TITLE
How to switch the stage from prod to test?

### ISSUE THREAD

**Issue by hiroki-gota** [awslabs/aws-serverless-express#49]
This repository code currently creates a stage 'prod', which is mentioned in:

* cloudformation.yaml
* packaged-sam.yaml
* simple-proxy-api.yaml

I've change the stage name to 'test' in the above files, which created the test stage successfully, however the prod stage has been removed. 

How could I create another stages while retaining the 'prod'?

Thanks.

**Comment by kahouieong** [comment]
I think you can create two 'Stage' resources in your CloudFormation stack. Once you finish your testing in 'test' stage, you can update the deployment id for the 'prod' stage resource. I have a prototype CloudFormation template below. You might be able to reuse the concepts on deploying the tested deployment from ```test``` stage to ```prod``` stage.

 ```
 {
    "Deployment20170221": {
      "Type" : "AWS::ApiGateway::Deployment",
      "Properties" : {
        "RestApiId" : { "Ref": "MyRestApi" }
      }
    },
    "Deployment20170304": {
      "Type" : "AWS::ApiGateway::Deployment",
      "Properties" : {
        "RestApiId" : { "Ref": "MyRestApi" }
      }
    },
    "Test" :{
      "Type" : "AWS::ApiGateway::Stage",
      "Properties" : {
        "DeploymentId" : { "Ref": "Deployment20170304" },
        "Description" : 'Dev',
        "RestApiId" : { "Ref": "MyRestApi" },
        "StageName" : 'test'
      }
    },
    "Prod": {
      "Type" : "AWS::ApiGateway::Stage",
      "Properties" : {
        "DeploymentId" : { "Ref": "Deployment20170221" },
        "Description" : 'Prod',
        "RestApiId" : { "Ref": "MyRestApi" },
        "StageName" : 'prod'
      }
    }
  } 
```

**Comment by brettstack** [comment]
It's worth pointing out that the example uses the AWS::Serverless::Api SAM resource type https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md. This resource type (currently) allows only one stage. By using the more flexible AWS::ApiGateway::Stage resource type, it may interfere with the `package` and `deploy` commands (unconfirmed).

**Comment by hiroki-gota** [comment]
Thanks for your response.

I've successfully created dev/qa/uat/prod stage as kahouieong suggested and package/deploy commands worked without any changes.

I've basically created 4 set of lambda functions and specified in the stage variables so each stage will point to a specific lambda function.
```
  Deployment20170428:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      RestApiId:
        Ref: "ApiGatewayApi"
      Description: "deployment"

  ApiGatewayApiQaStage:
    Type: "AWS::ApiGateway::Stage"
    Properties:
      StageName: "qa"
      Description: "QA Stage"
      RestApiId:
        Ref: "ApiGatewayApi"
      DeploymentId:
        Ref: "Deployment20170428"
      Variables:
        ServerlessExpressLambdaFunctionName: !Ref VicRlTagAdminApiFunctionQa
        Stack: "qa"
```

At the moment package/deploy command creates/updates all stages with the same code base as all Functions have the same CodeUri
```
ApiFunctionQa:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda.handler
      MemorySize: 1024
      Role: LambdaExecutionRole
      Runtime: nodejs4.3
      Timeout: 30
      Environment:
       Variables:
         TARGET_ENV: qa
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY
```

The generated packaged-sam.yaml contains the packaged s3 reference:
```
CodeUri: s3://my-api-function/486d6a80175a62f83bfa6f16209e9554
```

Your example has 2 deployment resources which seems to deploy a different version of code base:
```
"Deployment20170221": {
     "Type" : "AWS::ApiGateway::Deployment",
     "Properties" : {
       "RestApiId" : { "Ref": "MyRestApi" }
     }
   },
   "Deployment20170304": {
     "Type" : "AWS::ApiGateway::Deployment",
     "Properties" : {
       "RestApiId" : { "Ref": "MyRestApi" }
     }
   },
```

Could you please explain what are the relation to 'packaged s3 ref s3://my-api-function/486d6a80175a62f83bfa6f16209e9554' and these deployment resources?

My user stories would be:

- Given new features are just built, I want to deploy it to dev only
- Given I've verified the new feature, I want to push it to qa only
- Given QA's verified the new feature, I want to push it to uat only
- Given my customer's verified the new feature, I want to push it to prod

While I can do the above simply using AWS CLI for lambda (your example used to perform this by using the CLI instead of the cloudformation), I'd like to know the recommended way of doing this.

Thanks in advance.
