### ISSUE TITLE
Integration with AWS SQS

### ISSUE THREAD

**Issue by robertocerdasilva** [awslabs/aws-serverless-express#526]
Hi good morning. Is it possible if you can help me to solve the following problem?

I have an API with different endpoints. When creating a queue in AWS SQS, I need to execute the code or function within the /user endpoint (POST method)

**THE PROBLEM**
When executing the lambda function from SQS, the function does not go through any route or endpoint
Am I missing some setting?

My index.js   (/src/app/index.js)
```
import express, { json, urlencoded } from 'express'
import serverlessExpress from '@vendia/serverless-express'
import cors from 'cors'
import '../environment/index.js'

const app = express()

app.use(cors())
app.use(json())
app.use(urlencoded({ extended: false }))

app.get('/user/:user_id', (req, res) => {
    const { user_id } = req.params
    console.log(user_id)
    res.send(user_id)
})

app.post('/user', (req, res) => {
    const { data } = req.body
    console.log(data )

    // Logic...
    res.send(data)
})

// Run in LOCALHOST
if(process.env.LOCALSERVER) app.listen(5000)

// Run in AWS Lambda
export const handler = serverlessExpress({ app, eventSourceRoutes: { 'AWS_SQS': '/sqs' }})

```

My serverless.yml
```
functions:
    lambda-handler:
        handler: src/app/index.handler
        name: myName
        events:
            - http:
                path: /user
                method: post
            - sqs:
                arn:
                    Fn::GetAtt:
                        - MyQueue
                        - Arn

resources:
    Resources:
        MyQueue:
            Type: "AWS::SQS::Queue"
            Properties:
                QueueName: "MyQueue"
```

Thanks
