### ISSUE TITLE
CORS OPTIONS preflight request fails in AWS lambda

### ISSUE THREAD

**Issue by igoodwinVolly** [awslabs/aws-serverless-express#553]
I've narrowed down my application failure to the CORS configuration. **Note that this works when using Serverless Framework, but not this package serverless-express.** I'm migrating the API from Serverless to this package and testing on localhost:4200 with Angular.

I believe the issue is caused by a custom header, `x-api-key` that is sent from the front end to the back end.

In the browser, the Network tab in Chrome dev tools reveals a 503 preflight OPTIONS CORS error.

`Access to XMLHttpRequest at 'https://xxxxxxxxxx.execute-api.us-west-2.amazonaws.com/complicatedroute from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

AWS returns a 503 on all endpoints after the lambda function times out after 30 seconds.

Custom CORS configuration:

```js
app.use(
  cors({
    allowedHeaders: ['Accept', 'Authorization', 'Content-Type', 'x-api-key'],
    credentials: true,
    methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE', 'OPTIONS'],
    origin: [/\.mydomain\.com/, /localhost:4200/, /\.amplifyapp\.com/],
  })
);
```

If I add the same CORS configuration to the HttpApi CORS settings in the AWS Console, the same error occurs.

Also, in attempting to log the `getCurrentInvoke()` function at the top of app.js, it appears to be an empty object.

What's even more strange is the function may be stuck, as the log does not begin with START nor stop with END.

```
<html>
<body>
<!--StartFragment-->

2022-09-27T08:01:53.782-05:00 | 2022-09-27T13:01:53.782Z undefined INFO CURRENT INVOCATION
-- | --
  | 2022-09-27T08:01:53.783-05:00 | 2022-09-27T13:01:53.783Z undefined INFO {}
  | 2022-09-27T08:01:53.815-05:00 | START RequestId: 79a9afb8-f9b6-454d-a7e6-09647d828b86 Version: $LATEST
  | 2022-09-27T08:02:23.851-05:00 | END RequestId: 79a9afb8-f9b6-454d-a7e6-09647d828b86
  | 2022-09-27T08:02:23.851-05:00 | REPORT RequestId: 79a9afb8-f9b6-454d-a7e6-09647d828b86 Duration: 30034.44 ms Billed Duration: 30000 ms Memory Size: 2048 MB Max Memory Used: 116 MB Init Duration: 1059.86 ms
  | 2022-09-27T08:02:23.851-05:00 | 2022-09-27T13:02:23.851Z 79a9afb8-f9b6-454d-a7e6-09647d828b86 Task timed out after 30.03 seconds
  | 2022-09-27T08:02:24.896-05:00 | 2022-09-27T13:02:24.896Z undefined INFO CURRENT INVOCATION
  | 2022-09-27T08:02:24.897-05:00 | 2022-09-27T13:02:24.897Z undefined INFO {}

<!--EndFragment-->
</body>
</html>
```

I've followed this example: [basic-starter-api-gateway-v2-typescript](https://github.com/vendia/serverless-express/tree/mainline/examples/basic-starter-api-gateway-v2-typescript)

> NOTE The API works as expected if I remove every route, then implement a simple GET route and return a string.

And I've set up a successful Cloudformation / AWS SAM template for the service using this template.yaml file. I am confident the error does not lie in the configuration of the VPC for the lambda (which needs access to a Redis server). If there is an error here, please let me know!

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

# Use a github action workflow to run
# sam deploy --parameter-overrides Stage=${{ variable }}

Parameters:
  # Either dev, stage, or prod
  Stage:
    Description: An environment name prefixed to resource names
    Type: String
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.0.1.0/24
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.0.2.0/24
  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.0.3.0/24

Resources:
  # Lambda and API
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'LambdaLayer-${Stage}'
      Description: Contains the node_modules required to run the API Function.
      # Need to create the layer folder! Contains layer/nodejs/node_modules
      ContentUri: ./layer
      CompatibleArchitectures:
        - x86_64
        - arm64
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: DELETE

  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'HandlerFunction-${Stage}'
      Description: Handles the main logic for all endpoints in the API.
      Runtime: nodejs16.x
      Timeout: 30
      MemorySize: 2048
      PackageType: Zip
      CodeUri: ./main.zip
      Handler: src/index.handler
      Layers:
        - !Ref LambdaLayer
      # Can have Policies OR Role (not both)
      # Role: api-custom-role
      Policies:
        # Needed for lambda to access the VPC
        - AWSLambdaVPCAccessExecutionRole
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        SecurityGroupIds:
          - !Ref SecurityGroup
      Environment:
        Variables:

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      Description: !Sub ' API ${Stage}'

  # VPC
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [2, !GetAZs '']
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: Vpc

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    # DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      # RouteTableId: !Ref PrivateRouteTable2
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet2

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'API V2 SG'
      GroupDescription: 'Security Group configuration for the  API'
      VpcId: !Ref Vpc

  SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      SourceSecurityGroupId: !Ref SecurityGroup
      Description: Enables data to be received inbound from Redis
      IpProtocol: tcp
      FromPort: 6379
      ToPort: 6379

  SecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref SecurityGroup
      Description: Enables data to be sent outbound anywhere
      IpProtocol: -1
      CidrIp: 0.0.0.0/0

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref Vpc

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1

  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1

  PrivateSubnet2:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !Ref PrivateSubnet2

  SecurityGroup:
    Description: Security group with no ingress rule
    Value: !Ref SecurityGroup
```
